# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWJhYzk5YzQ2Njc2ZGVkNmI3ZGM2MTU4MTNjMGEzODI1Zjg1YTg1MWEyMzJlMWZiZDcxYmE0YTk4NjllOTZmN2QwYzA4MmVlN2QwMzYzMGZmMmY4ODEzYzJmYzE1NzA3MWE0Y2RlNmJlMGE5ZTliZTIxYTcxMjhjNGM0NDc0Y2M=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
